version: "3.9"

services:
  influxdb:
    image: influxdb:2.1
    hostname: influxdb
    ports:
      - 8086:8086
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: Confuzed
      DOCKER_INFLUXDB_INIT_USERNAME: influx
      DOCKER_INFLUXDB_INIT_PASSWORD: InfluxPassword-987!
      DOCKER_INFLUXDB_INIT_BUCKET: FileEvents
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: InfluxAdminToken987
    
  mq:
    image: rabbitmq:3-management
    hostname: mq
    environment:
      RABBITMQ_DEFAULT_USER: mrrabbit
      RABBITMQ_DEFAULT_PASS: R@bbit-987!
    restart: unless-stopped
    ports:
      - 15672:15672
