version: "3.9"

services:
  mq:
    image: rabbitmq:3
    hostname: mq
    environment:
      RABBITMQ_DEFAULT_USER: mrrabbit
      RABBITMQ_DEFAULT_PASS: R@bbit-987!
    restart: unless-stopped
    
  monitor:
    build:
      context: .
      dockerfile: FileEventing.Monitor/Dockerfile
    image: fileeventing-monitor:latest
    hostname: monitor-1
    depends_on:
      - mq
      - service
    command:
      - "wait-for-it"
      - "-h"
      - "mq"
      - "-p"
      - "5572"
      - "--"
      - "dotnet"
      - "/app/FileEventing.Monitor.dll"
    environment:
      FILEEVENTING_BUS__HOST: mq
      FILEEVENTING_BUS__USER: mrrabbit
      FILEEVENTING_BUS__PASSWORD: R@bbit-987!
      
  
  service:
    build:
      context: .
      dockerfile: FileEventing.Service/Dockerfile
    image: fileeventing-service:latest
    hostname: service-1
    depends_on:
      - mq
    command:
      - "wait-for-it"
      - "-h"
      - "mq"
      - "-p"
      - "5572"
      - "--"
      - "dotnet"
      - "/app/FileEventing.Service.dll"
    environment:
      FILEEVENTING_BUS__HOST: mq
      FILEEVENTING_BUS__USER: mrrabbit
      FILEEVENTING_BUS__PASSWORD: R@bbit-987!