version: "3.9"

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sql
    ports:
      - 1433:1433
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: SQL_dev_Secret-987!
      MSSQL_PID: Developer
      
  influxdb:
    image: influxdb:2.1
    hostname: influxdb
    ports:
      - 8086:8086
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: Confuzed
      DOCKER_INFLUXDB_INIT_USERNAME: influx
      DOCKER_INFLUXDB_INIT_PASSWORD: InfluxPassword-987!
      DOCKER_INFLUXDB_INIT_BUCKET: FileEvents
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: InfluxAdminToken987
    
  mq:
    image: rabbitmq:3-management
    hostname: mq
    environment:
      RABBITMQ_DEFAULT_USER: mrrabbit
      RABBITMQ_DEFAULT_PASS: R@bbit-987!
    restart: unless-stopped
    ports:
      - 15672:15672
    
  monitor:
    build:
      context: .
      dockerfile: FileEventing.Monitor/Dockerfile
    image: fileeventing-monitor:latest
    hostname: monitor-1
    depends_on:
      - mq
      - service
    restart: unless-stopped
    command:
      - "wait-for-it"
      - "-h"
      - "mq"
      - "-p"
      - "5572"
      - "--"
      - "dotnet"
      - "/app/FileEventing.Monitor.dll"
    environment:
      FILEEVENTING_BUS__HOST: mq
      FILEEVENTING_BUS__USER: mrrabbit
      FILEEVENTING_BUS__PASSWORD: R@bbit-987!
      
  
  service:
    build:
      context: .
      dockerfile: FileEventing.Service/Dockerfile
    image: fileeventing-service:latest
    hostname: service-1
    depends_on:
      - mq
      - sql
      - influxdb
    restart: unless-stopped
    command:
      - "wait-for-it"
      - "-h"
      - "mq"
      - "-p"
      - "5572"
      - "--"
      - "dotnet"
      - "/app/FileEventing.Service.dll"
    environment:
      FILEEVENTING_ConnectionStrings__Files: "Server=sql; Database=FileEventing; User Id=sa; Password=SQL_dev_Secret-987!"
      FILEEVENTING_BUS__HOST: mq
      FILEEVENTING_BUS__USER: mrrabbit
      FILEEVENTING_BUS__PASSWORD: R@bbit-987!
