version: "3.9"

volumes:
  grafana-storage:

services:
  influxdb:
    image: influxdb:2.1
    hostname: influxdb
    ports:
      - "8086:8086"
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: Confuzed
      DOCKER_INFLUXDB_INIT_USERNAME: rob
      DOCKER_INFLUXDB_INIT_PASSWORD: Password123
      DOCKER_INFLUXDB_INIT_BUCKET: FileEvents
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: InfluxAdminToken987
    
  mq:
    image: rabbitmq:3-management
    hostname: mq
    environment:
      RABBITMQ_DEFAULT_USER: mrrabbit
      RABBITMQ_DEFAULT_PASS: R@bbit-987!
    restart: unless-stopped
    ports:
      - "15672:15672"
        
  grafana:
    image: grafana/grafana-oss:latest
    hostname: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    
