version: "3.9"

services:
  monitor:
    build:
      context: ../.
      dockerfile: FileEventing.Monitor/Dockerfile
    image: fileeventing-monitor:latest
    hostname: monitor-1
    depends_on:
      - mq
      - service
    restart: unless-stopped
    command:
      - "wait-for-it"
      - "-h"
      - "mq"
      - "-p"
      - "5572"
      - "--"
      - "dotnet"
      - "/app/FileEventing.Monitor.dll"
    environment:
      FILEEVENTING_BUS__HOST: mq
      FILEEVENTING_BUS__USER: mrrabbit
      FILEEVENTING_BUS__PASSWORD: R@bbit-987!
  
  service:
    build:
      context: ../.
      dockerfile: FileEventing.Service/Dockerfile
    image: fileeventing-service:latest
    hostname: service-1
    depends_on:
      - mq
      - influxdb
    restart: unless-stopped
    command:
      - "wait-for-it"
      - "-h"
      - "mq"
      - "-p"
      - "5572"
      - "--"
      - "dotnet"
      - "/app/FileEventing.Service.dll"
    environment:
      FILEEVENTING_ConnectionStrings__Files: "Server=sql; Database=FileEventing; User Id=sa; Password=SQL_dev_Secret-987!"
      FILEEVENTING_BUS__HOST: mq
      FILEEVENTING_BUS__USER: mrrabbit
      FILEEVENTING_BUS__PASSWORD: R@bbit-987!
      FILEEVENTING_INFLUXDB__TOKEN: InfluxAdminToken987
      FILEEVENTING_INFLUXDB__BUCKET: FileEvents
      FILEEVENTING_INFLUXDB__SERVICEURI: http://influxdb:8086
      FILEEVENTING_INFLUXDB__ORGANISATION: Confuzed
      
